### PR TITLE
Normalised Admin1 Switzerland

### PR DESCRIPTION
**Pull request by corneliusroemer**
Fixes https://github.com/outbreak-info/outbreak.info/issues/348

### CODE REVIEW

**Comment by gkarthik** [comment]
@corneliusroemer can you confirm that these names are normalized based on GADM shapefiles? Thanks.

**Comment by corneliusroemer** [comment]
@gkarthik I didn't know you were using GADM. I normalised to the country name that had a valid level 2 isocode, so for example 'CHE_CH-ZH' as opposed to 'CHE_CH-None'. It may work, but I'm of course not certain that it does because I was treating normalization as a blackbox exercise. I'll have a look at GADM shapefiles to be certain if you don't want to experiment.

**Comment by gkarthik** [comment]
@corneliusroemer yes, please confirm that the names match the ones in the GADM admin1 shapefile. Thanks!

**Comment by AlaaALatif** [comment]
Hi @corneliusroemer, thanks for the contribution! Can you please resubmit your PR? It needs to be updated from a merge we ran today.

**Comment by corneliusroemer** [comment]
@gkarthik I'm happy to rebase, but can you share the GADM location names you use? I'm pretty sure they're correct, I based them off the names that are shown on the map itself on outbreak.info - that will most certainly work.

**Comment by corneliusroemer** [comment]
Properly done in #11

**Pull request closed without merging**
